version: '3.9'

services:
  backend:
    build:
      context: .
      container_name: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://ikramkml@localhost:5432/test
    volumes:
      - .:/app
    command: 
      flask run --host=0.0.0.0 --port=5000
